services:
  postgres:
    image: postgres:18-alpine
    container_name: ms-wallet-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_wallet_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-wallet
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
      - "${GRPC_PORT}:${GRPC_PORT}"
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    networks:
      - default
      - ilia-nodejs-challenge

volumes:
  postgres_wallet_data:

networks:
  ilia-nodejs-challenge:
    name: ilia-nodejs-challenge
    driver: bridge
